export const alertActionsTypes = {
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
};

export const registerActionsTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
};
export const authCheckerTyper = {
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
};

export const loginActionsTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
};

export const LOGOUT = "LOGOUT";

export const profileActionTypes = {
  GET_PROFILE: "GET_PROFILE",
  GET_PROFILES: "GET_PROFILES",
  GET_REPOS: "GET_REPOS",
  CLEAR_PROFILE: "CLEAR_PROFILE",
  PROFILE_ERROR: "PROFILE_ERROR",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
};
